version: '3' # Docker version
services:
    web: # Servicio
        build: .
        command: bundle exec rails db:migrate # es necesario pero se puede poner rake en lugar de rails
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
          - .:/myapp
        ports:
          - "3000:3000"
